apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
      app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
              - name: mysql
                image: mysql_image
                imagePullPolicy: Never
                ports:
                    - containerPort: 3306
                volumeMounts:
                    - name: mysql-volume
                      mountPath: /var/lib/mysql
            volumes:
                - name: mysql-volume
                  persistentVolumeClaim:
                      claimName: mysql-volume-claim
