apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-volume-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
      metallb.universe.tf/address-pool: default
      metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      name: ftp
      port: 20
      targetPort: 20
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: ftps-data
      port: 21000
      targetPort: 21000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
      app: ftps
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ftps
    template:
        metadata:
            labels:
                app: ftps
        spec:
            containers:
              - name: ftps
                image: ftps_image
                imagePullPolicy: Never
                ports:
                    - containerPort: 20
                    - containerPort: 21
                    - containerPort: 21000
                volumeMounts:
                    - name: ftps-volume
                      mountPath: /home/gshona
            volumes:
                - name: ftps-volume
                  persistentVolumeClaim:
                      claimName: ftps-volume-claim
