<?php
define( 'DB_NAME', 'gshona_db' );
define( 'DB_USER', 'admin' );
define( 'DB_PASSWORD', 'admin' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );
define('AUTH_KEY',         's*jf`v>[i4t9ESA*idk>GwN+-xerAYQ*9MSS%AZ.):rQ^P~ezrK&fT^U=iS3a2`7');
define('SECURE_AUTH_KEY',  '~5[hxKKm&Y#BlkW.9+)2n-r]~fx~zUE06=v-+T{`AC%ObIvV:bF08ym`b#i9K)d|');
define('LOGGED_IN_KEY',    'Mnj@s0H2!d-WX_kqXA3PGl[/-sVlY+PylM%sSG/wqoMqsS-PX|[zdSR>NKtTWR|`');
define('NONCE_KEY',        'LA0Ewo|~lQg->~<JAGYsS)(,BLg&{;.x+zp@d,~@}D|F<x>Abm=~FKd29cC2hF-y');
define('AUTH_SALT',        'IFW4RPe+2lrI$xhZK@=3F+$r/^,2)i*8#>{/Op*&Y:pY^&k_s7-tv2+~<]&F*f*:');
define('SECURE_AUTH_SALT', '^n)]-+_T)Aex|Hj}8!>/lZt|DD+Ne42h.^ZpJsM^20viXP17q08Tr:~%%L+afLpU');
define('LOGGED_IN_SALT',   '9HoIv]]|)N[eosd|I$+Q5=tq1u*h 3c^Kz1_++}R=!.-$+H+HIeqQ%Bthm^X-qE>');
define('NONCE_SALT',       'At)bm9!L.5bT-LsbNT$-D{}dJ=-/Cxy>A3vV)TK%;eq6nT3QhM(F>m/+HC`.`@[4');
$table_prefix = 'wp_';
define( 'WP_DEBUG', false );
define('WP_HOME', 'http://XXXXXXXXXX:5050' );
define('WP_SITEURL', 'http://XXXXXXXXXX:5050' );
require_once ABSPATH . 'wp-settings.php';
